apiVersion: v1
kind: Pod
metadata:
  name: backend-cka06-arch
  namespace: default
spec:
  containers:
  - name: memory-demo-ctr
    image: polinux/stress
    resources:
      requests:
        memory: "200Mi"
      limits:
        memory: "600Mi"
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "400M", "--vm-hang", "1"]
