apiVersion: v1
kind: Pod
metadata:
  name:  frontend-cka-arch-05
  namespace: default
spec:
  containers:
  - name: cpu-demo-ctr
    image: vish/stress
    resources:
      limits:
        cpu: "0.5"
      requests:
        cpu: "0.5"
    args:
    - -cpus
    - "1"
